### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by dzinks2009** [bennetgallein/TS3AB-API#2]
1

**Comment by FlareNetwork** [comment]
I dont think there is a Panel, this is a libary (bridge) to interact with TS3AudioBot.
If you have a bit of knowledge in PHP & HTML you can easily make your own Panel with this libary.

**Comment by bennetgallein** [comment]
Yes, that is totally correct. This is also called an API Wrapper. It offers a cleaner way to interact with TS3AudioBot over some functions so you dont need to make every call yourself. But you can easily integrate this into your own Frontend if you have some basic knowledge about PHP. 




Bennet Gallein


http://bennetgallein.de


bennet@intranetproject.net


+49 177 2489624







On Mon, Aug 13, 2018 at 2:56 AM +0200, "FlareCO" <notifications@github.com> wrote:












I dont think there is a Panel, this is a libary (bridge) to interact with TS3AudioBot.

If you have a bit of knowledge in PHP & HTML you can easily make your own Panel with this libary.
